Metrics/LineLength:
  Max: 100


Metrics/MethodLength:
  Max: 11


Style/Documentation:
  Enabled: false


Style/EmptyLines:
  Enabled: false


Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines


Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
