AllCops:
  Exclude:
    - lib/cucumber_lint.rb
    - lib/cucumber_lint/version.rb


Metrics/LineLength:
  Max: 100


Metrics/MethodLength:
  Max: 11


Style/EmptyLines:
  Enabled: false


Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines


Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
