consistent_empty_lines:
  enabled: true
  between_elements: 1
  between_scenario_outline_and_examples: 1


consistent_table_headers:
  enabled: true
  enforced_style: uppercase
  supported_styles:
    - lowercase  # column header
    - uppercase  # COLUMN HEADER


consistent_table_whitespace:
  enabled: true


no_repeating_keywords:
  enabled: true
